### PR TITLE
Add ontology ancestor mapping notebook

### PR DESCRIPTION
**Pull request by ebezzi**
Notebook used to compute ancestors for nodes in human, mouse and UBERON (only a subset) ontologies.

### CODE REVIEW

**Review by atolopko-czi — CHANGES_REQUESTED** [review]
* Suggest mentioning this in this [doc](https://github.com/chanzuckerberg/single-cell-curation/blob/ebezzi/add-ontology-ancestor-notebook/cellxgene_schema_cli/scripts/readme.md).
* And what if we put this notebook/script somewhere under [cellxgene_schema_cli/cellxgene_schema](https://github.com/chanzuckerberg/single-cell-curation/tree/ebezzi/add-ontology-ancestor-notebook/cellxgene_schema_cli/cellxgene_schema/) to keep it closer to related files?

**Comment by ebezzi** [comment]
> * Suggest mentioning this in this [doc](https://github.com/chanzuckerberg/single-cell-curation/blob/ebezzi/add-ontology-ancestor-notebook/cellxgene_schema_cli/scripts/readme.md).
> * And what if we put this notebook/script somewhere under [cellxgene_schema_cli/cellxgene_schema](https://github.com/chanzuckerberg/single-cell-curation/tree/ebezzi/add-ontology-ancestor-notebook/cellxgene_schema_cli/cellxgene_schema/) to keep it closer to related files?

Adding to the doc for sure, not that sure about adding it to `cellxgene_schema` - this is more of a static generation file and it's not quite related to the validator. @pablo-gar since you mostly work on this repo, what are your thoughts?

**Comment by pablo-gar** [comment]
I agree that for the moment we should not include under `cellxgene_schema_cli/cellxgene_schema`. However if at any point we need to put extra constraints in `obs["development_stage"]` for the validator, then we need to make sure to include ancestors in the reference static ontology files.

The work Emanuale did here is because ancestors and descendants cannot be extracted as usual with owlready2, thus that info is not included in the reference files at `cellxgene_schema_cli/cellxgene_schema/ontology_files/all_ontology.json.gz`. 

I may recommend we put this under `docs` to not clutter the root of the repo, @brianraymor any suggestions?

**Review by pablo-gar — COMMENTED** [review]
@ebezzi are you planning to use this for any sort of production stages? 

If so we have to make sure that we are pulling information from the pinned version of the ontologies as described in the schema v2.0.0. I believe your code pulls the latest version available in obo library.

**Comment by pablo-gar** [comment]
@ebezzi can you also please add a brief description of what the notebook does, maybe at the beginning of the notebook

**Review by atolopko-czi — APPROVED** [review]
Approving now, with my suggestions having been considered. Thanks!

**Comment by ebezzi** [comment]
@pablo-gar 

1. What about a `notebooks` folder?
2. Agree, if we increase the ontology constraints (or add new species) we will need to regenerate the files. I think this would be infrequent enough not to justify automating the process
3. This will be used in production. I think @brianraymor mentioned that we're not particularly concerned about having to regenerate the mappings often. When I ran the script, I downloaded the ontology files from the link you sent me and ran it from my machine, so they're the latest versions.
4. I will add a description, thanks for the suggestion!

**Comment by brianraymor** [comment]
Who is the audience for this notebook? I like Pablo's suggestion to use `notebooks`. 

The ontologies must match the [pinned versions](https://github.com/chanzuckerberg/single-cell-curation/blob/main/schema/2.0.0/schema.md#required-ontologies) in schema 2.0.0. HSAPDV and MMUSDV do not change much, but UBERON does.

**Comment by ebezzi** [comment]
@brianraymor The notebook is mostly meant for developers who want/need to regenerate the mapping files. Regenerating it won't be a big deal, but it should be a sporadic activity (say once per year), otherwise we might have to create some sort of automation for this.

**Review by pablo-gar — APPROVED** [review]

**Pull request merged**
